version: '3.2'
services:
  web:
    build: .
    command: mix phx.server
    links:
      - db
    volumes:
      - .:/work
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db